class SessionData {
  final String name;
  final String sansName;
  final String imageurl;
  final String benefits;
  final String procedure;

  SessionData(this.name, this.sansName, this.imageurl, this.procedure, this.benefits);
}

final yoga1 = SessionData('Salute Pose', 'Urdhva Hastasana', 'assets/yogaposes/031-salute.png', 'While the legs are grounded in padmasana, or lotus pose, the whole of the upper body is stretched upwards with the arms over the head and palms pressed together', 'Stretches the belly, shoulders and armpits, and Improves digestion.');
final yoga2 = SessionData('Warrior Pose', 'Virabhadrasana', 'assets/yogaposes/032-warrior.png', 'Step 1\nSit with your spine erect and legs spread straight out.\n\nStep 2\nNow bend your knees and bring your feet towards the pelvis. The soles of your feet should touch each other.\n\nStep 3\nGrab your feet tightly with your hands. You may place the hands underneath the feet for support\n\nStep 4\nMake an effort to bring the heels as close to the genitals as possible\n\nStep 5\nTake a deep breath in. Breathing out, press the thighs and knees downward towards the floor. Make a gentle effort to keep pressing them downward.', 'Stretches the chest and lungs, shoulders, neck, belly, thighs, calves, and ankles');
final yoga3 = SessionData('Tree Pose', 'Vrikshasan', 'assets/yogaposes/027-tree.png', 'Step 1\nSit in Dandasana (Staff Pose), then bend your knees and put your feet on the floor. Slide your left foot under the right knee to the outside of the right hip. Then cross your right leg over the left, stacking the right knee on top of the left, and bring the right foot to the outside of the left hip. Try to bring the heels equidistant from the hips: with the right leg on top you’ll have to tug the right heel in closer to the left hip. Sit evenly on the sitting bones.\n\nStep 2\nInhale and stretch your right arm straight out to the right, parallel to the floor. Rotate your arm inwardly; the thumb will turn first toward the floor, then point toward the wall behind you, with the palm facing the ceiling. This movement will roll your right shoulder slightly up and forward, and round your upper back. With a full exhalation, sweep the arm behind your torso and tuck the forearm in the hollow of your lower back, parallel to your waist, with the right elbow against the right side of your torso. Roll the shoulder back and down, then work the forearm up your back until it is parallel to your spine. The back of your hand will be between your shoulder blades. See that your right elbow doesn’t slip away from the right side of your torso.\n\nStep 3\nNow inhale and stretch your left arm straight forward, pointing toward the opposite wall, parallel to the floor. Turn the palm up and, with another inhalation, stretch the arm straight up toward the ceiling, palm turned back. Lift actively through your left arm, then with an exhalation, bend the elbow and reach down for the right hand. If possible, hook the right and left fingers.\n\nStep 4\nLift the left elbow toward the ceiling and, from the back armpit, descend the right elbow toward the floor. Firm your shoulder blades against your back ribs and lift your chest. Try to keep the left arm right beside the left side of your head.\n\nStep 5\nStay in this pose about 1 minute. Release the arms, uncross the legs, and repeat with the arms and legs reversed for the same length of time. Remember that whichever leg is on top, the same-side arm is lower.', 'Stretches the ankles, hips and thighs, shoulders, armpits and triceps, and chest');

final allYogas = [yoga1, yoga3, yoga2];
